import React, { useState } from "react";
import { DateCalendar } from "@mui/x-date-pickers/DateCalendar";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import Button from "@mui/material/Button";
import styles from "../styles/DateTime.module.css";

export default function ChooseDateTime({ onNext }) {
  const [selectedDate, setSelectedDate] = useState(null);
  const [time, setTime] = useState(null);
  const [view, setView] = useState("calendar");

  const handleDateNext = () => {
    if (selectedDate) {
      setView("time");
    }
  };

  const handleTimeSelect = (slot) => {
    setTime(slot);
    if (selectedDate && slot) {
      onNext(selectedDate, slot);
    }
  };

  // A function to generate time slots (hard-coded placeholder for now) for the chosen barber.
  const generateTimeSlots = () => {
    const slots = [];
    const startTime = new Date();
    startTime.setHours(8, 0, 0, 0); // Start at 8:00 AM

    for (let i = 0; i < 18; i++) {
      // 18 slots for 30-minute intervals up to 5:00 PM
      const slotTime = new Date(startTime.getTime() + i * 30 * 60000); // 30-minute intervals
      const hours = slotTime.getHours();
      const minutes = slotTime.getMinutes();
      const formattedTime = `${hours % 12 || 12}:${
        minutes === 0 ? "00" : minutes
      } ${hours < 12 ? "AM" : "PM"}`;
      slots.push(formattedTime);
    }

    return slots;
  };

  const timeSlots = generateTimeSlots();

  return (
    // MUI component implemented using Github Copilot (GPT 4o)
    <div className={styles.dateTime}>
      {view === "calendar" && (
        <>
          <LocalizationProvider dateAdapter={AdapterDayjs}>
            <DateCalendar
              value={selectedDate}
              onChange={(newValue) => setSelectedDate(newValue)}
              className={styles.calendar}
              sx={{
                "& .MuiPickersDay-root.Mui-selected": {
                  backgroundColor: "#35281f",
                  "&:hover": {
                    backgroundColor: "#35281f",
                  },
                },
                "& .MuiPickersDay-root.Mui-selected:focus": {
                  backgroundColor: "#35281f",
                },
                "& .MuiPickersDay-today": {
                  borderColor: "#35281f",
                },
              }}
            />
          </LocalizationProvider>
          {selectedDate && (
            <Button
              onClick={handleDateNext}
              variant="contained"
              sx={{
                marginTop: "2rem",
                backgroundColor: "#35281f",
                color: "#fafafa",
                "&:hover": {
                  backgroundColor: "#fafafa",
                  color: "#35281f",
                },
              }}
            >
              Next
            </Button>
          )}
        </>
      )}

      {/* Generated by GPT4o */}
      {view === "time" && (
        <div className={styles.timeSlots}>
          <h2>Available Slots</h2>
          <div className={styles.timeSlotsContainer}>

            {/* map generates an array of buttons and populates them with the time slots */}
            {timeSlots.map((slot) => (
              <Button
                key={slot}
                variant={slot === time ? "contained" : "outlined"}
                onClick={() => handleTimeSelect(slot)}
                className={styles.timeSlot}
              >
                {slot}
              </Button>
            ))}
          </div>
          {time && (
            <Button
              onClick={() => onNext(selectedDate, time)}
              variant="contained"
              sx={{
                marginTop: "2rem",
                backgroundColor: "#35281f",
                color: "#fafafa",
                "&:hover": {
                  backgroundColor: "#fafafa",
                  color: "#35281f",
                },
              }}
            >
              Confirm
            </Button>
          )}
        </div>
      )}
    </div>
  );
}
